// <auto-generated />
using System;
using AiLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiLabDbContext))]
    [Migration("20260917223937_AddExecutionPlanNodeIdentity")]
    partial class AddExecutionPlanNodeIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AiLab.Core.Execution.ExecutionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualModel")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiRequestId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCachedInputCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedInputCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedOutputCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedTotalCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstOutputTokenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstResponseEventAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedProviderRequestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawProviderResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequestSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResponseSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiRequestId");

                    b.HasIndex("PlanNodeId");

                    b.ToTable("ExecutionRuns");
                });

            modelBuilder.Entity("AiLab.Core.ExecutionPlans.ExecutionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ExecutionPlans");
                });

            modelBuilder.Entity("AiLab.Core.ExecutionPlans.ExecutionPlanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("CumulativeRequestDuration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionRunIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Groups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanGraphSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalEstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPlanId");

                    b.ToTable("ExecutionPlanRuns");
                });

            modelBuilder.Entity("AiLab.Core.Models.ModelCatalogProviderStatus", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRefreshAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProviderId");

                    b.ToTable("ModelCatalogProviderStatuses");
                });

            modelBuilder.Entity("AiLab.Core.Models.ProviderModel", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CachedInputPricePerMillion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContextWindowTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputModalities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InputPricePerMillion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputModalities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OutputPricePerMillion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportedReasoningLevels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsPromptCacheKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStructuredOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsToolCalling")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderId", "ModelId");

                    b.ToTable("ProviderModels");
                });

            modelBuilder.Entity("AiLab.Core.Requests.AiRequestDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputBindings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptCacheKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StreamingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructuredOutputSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AiLab.Core.Workspaces.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AiLab.Core.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("AiLab.Core.Workspaces.WorkspaceVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("WorkspaceVariables");
                });

            modelBuilder.Entity("AiLab.Core.Execution.ExecutionRun", b =>
                {
                    b.HasOne("AiLab.Core.Requests.AiRequestDefinition", null)
                        .WithMany()
                        .HasForeignKey("AiRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AiLab.Core.Execution.FailureInfo", "Failure", b1 =>
                        {
                            b1.Property<Guid>("ExecutionRunId");

                            b1.Property<string>("ExceptionType");

                            b1.Property<int?>("HttpStatus");

                            b1.Property<string>("Message");

                            b1.Property<string>("ProviderError");

                            b1.Property<int>("RetryCount");

                            b1.Property<bool>("StreamingStarted");

                            b1.HasKey("ExecutionRunId");

                            b1.ToTable("ExecutionRuns");

                            b1
                                .ToJson("Failure")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionRunId");
                        });

                    b.OwnsOne("AiLab.Core.Execution.TokenUsage", "Usage", b1 =>
                        {
                            b1.Property<Guid>("ExecutionRunId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CachedInputTokens")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("InputTokens")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OutputTokens")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReasoningTokens")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalTokens")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ExecutionRunId");

                            b1.ToTable("ExecutionRuns");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionRunId");
                        });

                    b.Navigation("Failure");

                    b.Navigation("Usage")
                        .IsRequired();
                });

            modelBuilder.Entity("AiLab.Core.ExecutionPlans.ExecutionPlan", b =>
                {
                    b.HasOne("AiLab.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AiLab.Core.ExecutionPlans.ExecutionPlanDependency", "Dependencies", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ExecutionPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FromNodeId")
                                .HasColumnType("TEXT")
                                .HasColumnName("FromRequestId");

                            b1.Property<Guid>("ToNodeId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ToRequestId");

                            b1.HasKey("Id");

                            b1.HasIndex("ExecutionPlanId");

                            b1.ToTable("ExecutionPlanDependencies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExecutionPlanId");
                        });

                    b.OwnsMany("AiLab.Core.ExecutionPlans.ExecutionPlanRequest", "Requests", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AiRequestId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ExecutionPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsFinalOutput")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ExecutionPlanId");

                            b1.ToTable("ExecutionPlanRequests", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExecutionPlanId");
                        });

                    b.Navigation("Dependencies");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("AiLab.Core.ExecutionPlans.ExecutionPlanRun", b =>
                {
                    b.HasOne("AiLab.Core.ExecutionPlans.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("ExecutionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiLab.Core.Requests.AiRequestDefinition", b =>
                {
                    b.HasOne("AiLab.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AiLab.Core.Requests.ContentBlock", "CachedContext", b1 =>
                        {
                            b1.Property<Guid>("AiRequestDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AttachmentIds")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AiRequestDefinitionId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("AiRequestDefinitionId");
                        });

                    b.OwnsOne("AiLab.Core.Requests.ContentBlock", "UserContext", b1 =>
                        {
                            b1.Property<Guid>("AiRequestDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AttachmentIds")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AiRequestDefinitionId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("AiRequestDefinitionId");
                        });

                    b.OwnsOne("AiLab.Core.Requests.ReasoningConfig", "Reasoning", b1 =>
                        {
                            b1.Property<Guid>("AiRequestDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Effort")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AiRequestDefinitionId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("AiRequestDefinitionId");
                        });

                    b.OwnsOne("AiLab.Core.Requests.RetryPolicy", "RetryPolicy", b1 =>
                        {
                            b1.Property<Guid>("AiRequestDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BaseBackoffMs")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxRetries")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AiRequestDefinitionId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("AiRequestDefinitionId");
                        });

                    b.Navigation("CachedContext")
                        .IsRequired();

                    b.Navigation("Reasoning");

                    b.Navigation("RetryPolicy")
                        .IsRequired();

                    b.Navigation("UserContext")
                        .IsRequired();
                });

            modelBuilder.Entity("AiLab.Core.Workspaces.Attachment", b =>
                {
                    b.HasOne("AiLab.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiLab.Core.Workspaces.WorkspaceVariable", b =>
                {
                    b.HasOne("AiLab.Core.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
